#!/bin/sh
set -e

# PostgreSQL settings
PGDATA="${PGDATA:-/var/lib/postgresql/data}"
PGSOCKET="/run/postgresql"
# Outbound network firewall: domain-level egress filtering via tinyproxy
OUTBOUND_FIREWALL="${OUTBOUND_FIREWALL:-true}"
OUTBOUND_ALLOWLIST="${OUTBOUND_ALLOWLIST:-crates.io,static.crates.io,docs.rs,api.osv.dev}"

# tinyproxy settings (internal, not user-facing)
TINYPROXY_PORT=18888
TINYPROXY_CONF="/etc/tinyproxy/tinyproxy.conf"
TINYPROXY_FILTER="/etc/tinyproxy/allowlist"

# First-run: initialize the database cluster (as postgres user)
if [ ! -f "$PGDATA/PG_VERSION" ]; then
    su-exec postgres initdb -D "$PGDATA" --auth=trust --no-instructions
fi

# Remove stale PID file left behind after a hard container stop
rm -f "$PGDATA/postmaster.pid"

# Start postgres in the background as postgres user (unix socket only, no TCP)
su-exec postgres pg_ctl start -D "$PGDATA" -l "$PGDATA/postgres.log" -o "-k $PGSOCKET -h ''"

# Wait for readiness
until su-exec postgres pg_isready -h "$PGSOCKET" -q; do sleep 0.1; done

# Create the application database on first run
su-exec postgres createdb -h "$PGSOCKET" rust_mcp 2>/dev/null || true

if [ "$OUTBOUND_FIREWALL" = "true" ]; then
    echo "firewall: configuring tinyproxy egress filter"
    echo "firewall: allowed domains: $OUTBOUND_ALLOWLIST"

    # --- Generate domain allowlist filter file ---
    # Each domain gets two regex entries: exact match and subdomain match.
    # tinyproxy matches these against the CONNECT host for HTTPS requests.
    : > "$TINYPROXY_FILTER"
    for host in $(echo "$OUTBOUND_ALLOWLIST" | tr ',' ' '); do
        escaped=$(echo "$host" | sed 's/\./\\./g')
        echo "^${escaped}$" >> "$TINYPROXY_FILTER"
        echo "\.${escaped}$" >> "$TINYPROXY_FILTER"
    done

    # --- Generate tinyproxy configuration ---
    cat > "$TINYPROXY_CONF" <<EOF
# Auto-generated by docker-entrypoint.sh — do not edit manually.
# Domain-level egress filtering for rust-mcp.

User nobody
Group nobody

Port ${TINYPROXY_PORT}
Listen 127.0.0.1

# Only allow connections from localhost
Allow 127.0.0.1
Allow ::1

# Only allow CONNECT tunnels to port 443 (HTTPS)
ConnectPort 443

# Domain allowlist: deny by default, allow only listed domains
Filter "${TINYPROXY_FILTER}"
FilterDefaultDeny Yes

# Suppress Via header to avoid confusing upstream servers
DisableViaHeader Yes

# Connection limits
MaxClients 100
Timeout 600

# Logging: warnings and above go to syslog (visible via docker exec)
LogLevel Warning
Syslog On
EOF

    # Start tinyproxy
    tinyproxy -c "$TINYPROXY_CONF"

    # Wait for tinyproxy to be ready (up to 3 seconds)
    attempts=0
    while [ $attempts -lt 30 ]; do
        if pgrep -x tinyproxy > /dev/null 2>&1; then
            break
        fi
        sleep 0.1
        attempts=$((attempts + 1))
    done

    if ! pgrep -x tinyproxy > /dev/null 2>&1; then
        echo "firewall: ERROR: tinyproxy failed to start" >&2
        exit 1
    fi

    # Set proxy environment variables — reqwest reads these automatically
    export HTTPS_PROXY="http://127.0.0.1:${TINYPROXY_PORT}"
    export HTTP_PROXY="http://127.0.0.1:${TINYPROXY_PORT}"
    export NO_PROXY="127.0.0.1,localhost,::1"

    echo "firewall: tinyproxy started on port ${TINYPROXY_PORT}"
    echo "firewall: egress filter active"
fi

# Ensure the data directory exists and is writable by the app user
MCP_DATA_DIR="${MCP_DATA_DIR:-/var/lib/rust-mcp}"
mkdir -p "$MCP_DATA_DIR"
chown rust-mcp:rust-mcp "$MCP_DATA_DIR"

# Drop privileges: hand off PID 1 to the app as rust-mcp user
exec su-exec rust-mcp /usr/local/bin/rust-mcp "$@"
