/// `crate.alternatives` handler.
pub mod alternatives;
/// `crate.api_diff` handler.
pub mod api_diff;
/// `crate.api` handler.
pub mod api_surface;
/// `crate.compare` handler.
pub mod compare;
/// `crate.compatibility` and `crate.compatibility_matrix` handlers.
pub mod compatibility;
/// `crate.deprecated` handler.
pub mod deprecated;
/// `crate.derive_macros` handler.
pub mod derive_macros;
/// `crate.error_types` handler.
pub mod error_types;
/// `crate.features` handler.
pub mod features;
/// `crate.graph` handler.
pub mod graph;
/// `crate.hotspots` handler.
pub mod hotspots;
/// `crate.import_path` handler.
pub mod import_path;
/// `crate.intel` handler.
pub mod intel;
/// `crate.license_check` handler.
pub mod license;
/// `crate.migration_path` handler.
pub mod migration_path;
/// `crate.re_exports` handler.
pub mod re_exports;
/// `crate.search` handler.
pub mod search;
/// `crate.trait_impls` handler.
pub mod trait_impls;
/// `crate.type_info` handler.
pub mod type_info;
/// `crate.usage_patterns` handler.
pub mod usage_patterns;
/// `crate.versions` handler.
pub mod versions;
