/// `crate_alternatives` handler.
pub mod alternatives;
/// `crate_api_diff` handler.
pub mod api_diff;
/// `crate_api` handler.
pub mod api_surface;
/// `crate_compare` handler.
pub mod compare;
/// `crate_compatibility` and `crate_compatibility_matrix` handlers.
pub mod compatibility;
/// `crate_deprecated` handler.
pub mod deprecated;
/// `crate_derive_macros` handler.
pub mod derive_macros;
/// `crate_error_types` handler.
pub mod error_types;
/// `crate_features` handler.
pub mod features;
/// `crate_graph` handler.
pub mod graph;
/// `crate_hotspots` handler.
pub mod hotspots;
/// `crate_import_path` handler.
pub mod import_path;
/// `crate_intel` handler.
pub mod intel;
/// `crate_license_check` handler.
pub mod license;
/// `crate_migration_path` handler.
pub mod migration_path;
/// `crate_re_exports` handler.
pub mod re_exports;
/// `crate_search` handler.
pub mod search;
/// `crate_trait_impls` handler.
pub mod trait_impls;
/// `crate_type_info` handler.
pub mod type_info;
/// `crate_usage_patterns` handler.
pub mod usage_patterns;
/// `crate_versions` handler.
pub mod versions;
